package laya

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The reference environment the golden vectors under testdata/ were generated
// against. These are the pins scripts/requirements-ref.txt calls "the contract":
// a silent upstream tokenizer change is the realistic way parity regresses (R6),
// and it regresses without any commit in this repo.
//
// Test-only on purpose. Nothing in the library reads them yet, and exporting a
// constant the public API does not need would be harder to remove than to add.
// M4 promotes them if the pure-Go tokenizer needs to assert a target at runtime.
const (
	targetTokenizersVersion   = "0.23.2"
	targetTransformersVersion = "5.17.0"
)

// targetCompute is what produced the numbers (task 1.7.2). PLAN.md section 8
// promises the Go port lands "within 1e-4 of PyTorch", and that tolerance only
// means something against a stated device, dtype and attention implementation:
// the same weights under fp16, or under eager attention instead of sdpa, are a
// different reference. Recording it in the header turns an assumption into a
// check, the same move task 1.3.6 made for the tokenizer configs.
var targetCompute = computeBlock{
	Device:       "cpu",
	Dtype:        "float32",
	Attn:         "sdpa",
	TorchThreads: 1,
}

// computeBlock is the header's "compute" record. A pointer field on
// goldenHeader distinguishes "absent" from "present but zero", which matters:
// an absent block is a fixture generated before 1.7.2 and is exactly what this
// test exists to catch.
type computeBlock struct {
	Device       string `json:"device"`
	Dtype        string `json:"dtype"`
	Attn         string `json:"attn"`
	TorchThreads int    `json:"torch_threads"`
}

// goldenHeader is the first line of every testdata/*.jsonl file. Only the fields
// this test enforces are modelled; the generator writes more.
type goldenHeader struct {
	Kind     string            `json:"kind"`
	Fixture  string            `json:"fixture"`
	Versions map[string]string `json:"versions"`
	Compute  *computeBlock     `json:"compute"`
}

// TestGoldenProvenance asserts that every golden vector was generated by the
// reference environment this port targets (PLAN.md tasks 1.4 and 1.7.3).
//
// It globs rather than taking a file list: a fixture added later is then covered
// without anyone remembering to register it, which is the failure mode a list has.
func TestGoldenProvenance(t *testing.T) {
	paths, err := filepath.Glob(filepath.Join("testdata", "*.jsonl"))
	if err != nil {
		t.Fatalf("glob testdata/*.jsonl: %v", err)
	}
	if len(paths) == 0 {
		t.Fatal("no testdata/*.jsonl files; the golden corpus is the point of M1, " +
			"so an empty match is a broken checkout rather than nothing to do")
	}

	for _, path := range paths {
		t.Run(filepath.Base(path), func(t *testing.T) {
			for _, err := range checkProvenance(path) {
				t.Error(err)
			}
		})
	}
}

// TestGoldenProvenanceRejects drives checkProvenance against deliberately
// corrupted copies (tasks 1.4.3 and 1.7.3). A provenance test that cannot fail
// is worse than none: it looks like evidence while proving nothing. Each case
// names a way the corpus could rot in practice, not a synthetic mutation.
func TestGoldenProvenanceRejects(t *testing.T) {
	good, err := os.ReadFile(filepath.Join("testdata", "render.jsonl"))
	if err != nil {
		t.Fatalf("read the known-good fixture: %v", err)
	}
	head, body, found := strings.Cut(string(good), "\n")
	if !found {
		t.Fatal("render.jsonl has no second line; the corruption cases need a body to keep")
	}

	for _, tc := range []struct {
		name string
		// mutate edits the parsed header; nil means the header is dropped entirely.
		mutate func(h map[string]any)
		// want is a substring the failure must mention, so the test pins the
		// diagnosis and not merely the fact that something failed.
		want string
	}{
		{
			name:   "upstream tokenizer bumped without regenerating",
			mutate: func(h map[string]any) { h["versions"].(map[string]any)["tokenizers"] = "0.99.0" },
			want:   "tokenizers",
		},
		{
			name:   "regenerated under a different attention implementation",
			mutate: func(h map[string]any) { h["compute"].(map[string]any)["attn"] = "eager" },
			want:   "attn",
		},
		{
			name:   "regenerated on a GPU in half precision",
			mutate: func(h map[string]any) { h["compute"].(map[string]any)["device"] = "cuda" },
			want:   "device",
		},
		{
			name:   "generated before task 1.7.2 added the compute block",
			mutate: func(h map[string]any) { delete(h, "compute") },
			want:   "compute",
		},
		{
			name:   "hand-edited so the header is gone",
			mutate: nil,
			want:   "header",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			var content string
			if tc.mutate == nil {
				content = body
			} else {
				var h map[string]any
				if err := json.Unmarshal([]byte(head), &h); err != nil {
					t.Fatalf("parse the known-good header: %v", err)
				}
				tc.mutate(h)
				b, err := json.Marshal(h)
				if err != nil {
					t.Fatalf("re-marshal the corrupted header: %v", err)
				}
				content = string(b) + "\n" + body
			}

			path := filepath.Join(t.TempDir(), "render.jsonl")
			if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
				t.Fatalf("write the corrupted copy: %v", err)
			}

			errs := checkProvenance(path)
			if len(errs) == 0 {
				t.Fatalf("checkProvenance accepted a corrupted fixture (%s); "+
					"the provenance check is a no-op that still reports success", tc.name)
			}
			var joined strings.Builder
			for _, err := range errs {
				joined.WriteString(err.Error())
			}
			if !strings.Contains(joined.String(), tc.want) {
				t.Errorf("failure does not mention %q, so it does not name the cause:\n%s",
					tc.want, joined.String())
			}
		})
	}

	// The empty-file case cannot go through the table: there is no header to mutate.
	t.Run("truncated to nothing", func(t *testing.T) {
		path := filepath.Join(t.TempDir(), "render.jsonl")
		if err := os.WriteFile(path, nil, 0o600); err != nil {
			t.Fatalf("write the empty copy: %v", err)
		}
		if errs := checkProvenance(path); len(errs) == 0 {
			t.Fatal("checkProvenance accepted an empty file")
		}
	})
}

// checkProvenance returns one error per violation rather than calling t.Error
// itself, so TestGoldenProvenanceRejects can assert that a corrupt fixture is
// refused. A checker that can only fail a test cannot be tested.
func checkProvenance(path string) []error {
	h, err := readHeader(path)
	if err != nil {
		return []error{err}
	}

	// 1.4.3: a file with no header is worse than a missing file. It looks
	// like evidence while proving nothing about where it came from.
	if h.Kind != "header" {
		return []error{fmt.Errorf("first line has kind %q, want \"header\": %s carries no provenance",
			h.Kind, path)}
	}

	var errs []error
	if want := strings.TrimSuffix(filepath.Base(path), ".jsonl"); h.Fixture != want {
		errs = append(errs, fmt.Errorf("header fixture = %q, want %q (file renamed without regenerating?)",
			h.Fixture, want))
	}

	for _, c := range []struct{ key, want string }{
		{"tokenizers", targetTokenizersVersion},
		{"transformers", targetTransformersVersion},
	} {
		got, ok := h.Versions[c.key]
		if !ok {
			errs = append(errs, fmt.Errorf("header records no %q version; task 1.3.6 requires it", c.key))
			continue
		}
		if got != c.want {
			errs = append(errs, fmt.Errorf("%s = %q, want %q\n"+
				"The corpus and the Go port now target different reference "+
				"environments. Either scripts/requirements-ref.txt moved and "+
				"testdata/ was not regenerated, or it was regenerated against "+
				"an unpinned venv. Regenerating is a reviewed diff (R6).",
				c.key, got, c.want))
		}
	}

	return append(errs, checkCompute(h.Compute)...)
}

// checkCompute enforces task 1.7.2's header block. Section 8's "within 1e-4 of
// PyTorch" is a claim about a specific run; a vector that cannot say which run
// cannot support it.
func checkCompute(got *computeBlock) []error {
	if got == nil {
		return []error{fmt.Errorf("header has no \"compute\" block; task 1.7.2 requires "+
			"%+v, and without it section 8's 1e-4 tolerance names no reference run",
			targetCompute)}
	}
	if *got == targetCompute {
		return nil
	}
	return []error{fmt.Errorf("compute = %+v, want %+v\n"+
		"The vectors were produced by a different run than the port targets. "+
		"device/dtype/attn each change the numbers at the fourth decimal or worse "+
		"(D7 is the cautionary case), so this is a regeneration, not a tolerance.",
		*got, targetCompute)}
}

// readHeader reads only the first line. The corpus runs to megabytes and the
// provenance check has no use for the cases.
func readHeader(path string) (goldenHeader, error) {
	var h goldenHeader

	f, err := os.Open(path)
	if err != nil {
		return h, fmt.Errorf("open %s: %w", path, err)
	}
	defer f.Close()

	sc := bufio.NewScanner(f)
	// logits.jsonl carries whole logit tensors on one line, well past the 64 KiB
	// default. The header itself is small, but Scan fails on the file, not the line.
	sc.Buffer(make([]byte, 0, 64*1024), 16*1024*1024)
	if !sc.Scan() {
		if err := sc.Err(); err != nil {
			return h, fmt.Errorf("read %s: %w", path, err)
		}
		return h, fmt.Errorf("%s is empty; it carries no header (task 1.4.3)", path)
	}

	if err := json.Unmarshal(sc.Bytes(), &h); err != nil {
		return h, fmt.Errorf("first line of %s is not JSON: %w", path, err)
	}
	return h, nil
}
