package laya

import (
	"bufio"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The reference environment the golden vectors under testdata/ were generated
// against. These are the pins scripts/requirements-ref.txt calls "the contract":
// a silent upstream tokenizer change is the realistic way parity regresses (R6),
// and it regresses without any commit in this repo.
//
// Test-only on purpose. Nothing in the library reads them yet, and exporting a
// constant the public API does not need would be harder to remove than to add.
// M4 promotes them if the pure-Go tokenizer needs to assert a target at runtime.
const (
	targetTokenizersVersion   = "0.23.2"
	targetTransformersVersion = "5.17.0"
)

// goldenHeader is the first line of every testdata/*.jsonl file. Only the fields
// this test enforces are modelled; the generator writes more.
type goldenHeader struct {
	Kind     string            `json:"kind"`
	Fixture  string            `json:"fixture"`
	Versions map[string]string `json:"versions"`
}

// TestGoldenProvenance asserts that every golden vector was generated by the
// reference environment this port targets (PLAN.md task 1.4).
//
// It globs rather than taking a file list: a fixture added later is then covered
// without anyone remembering to register it, which is the failure mode a list has.
func TestGoldenProvenance(t *testing.T) {
	paths, err := filepath.Glob(filepath.Join("testdata", "*.jsonl"))
	if err != nil {
		t.Fatalf("glob testdata/*.jsonl: %v", err)
	}
	if len(paths) == 0 {
		t.Fatal("no testdata/*.jsonl files; the golden corpus is the point of M1, " +
			"so an empty match is a broken checkout rather than nothing to do")
	}

	for _, path := range paths {
		t.Run(filepath.Base(path), func(t *testing.T) {
			h := readHeader(t, path)

			// 1.4.3: a file with no header is worse than a missing file. It looks
			// like evidence while proving nothing about where it came from.
			if h.Kind != "header" {
				t.Fatalf("first line has kind %q, want \"header\": %s carries no provenance",
					h.Kind, path)
			}
			if want := strings.TrimSuffix(filepath.Base(path), ".jsonl"); h.Fixture != want {
				t.Errorf("header fixture = %q, want %q (file renamed without regenerating?)",
					h.Fixture, want)
			}

			for _, c := range []struct{ key, want string }{
				{"tokenizers", targetTokenizersVersion},
				{"transformers", targetTransformersVersion},
			} {
				got, ok := h.Versions[c.key]
				if !ok {
					t.Errorf("header records no %q version; task 1.3.6 requires it", c.key)
					continue
				}
				if got != c.want {
					t.Errorf("%s = %q, want %q\n"+
						"The corpus and the Go port now target different reference "+
						"environments. Either scripts/requirements-ref.txt moved and "+
						"testdata/ was not regenerated, or it was regenerated against "+
						"an unpinned venv. Regenerating is a reviewed diff (R6).",
						c.key, got, c.want)
				}
			}
		})
	}
}

// readHeader reads only the first line. The corpus runs to megabytes and the
// provenance check has no use for the cases.
func readHeader(t *testing.T, path string) goldenHeader {
	t.Helper()

	f, err := os.Open(path)
	if err != nil {
		t.Fatalf("open %s: %v", path, err)
	}
	defer f.Close()

	sc := bufio.NewScanner(f)
	// logits.jsonl carries whole logit tensors on one line, well past the 64 KiB
	// default. The header itself is small, but Scan fails on the file, not the line.
	sc.Buffer(make([]byte, 0, 64*1024), 16*1024*1024)
	if !sc.Scan() {
		if err := sc.Err(); err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		t.Fatalf("%s is empty; it carries no header (task 1.4.3)", path)
	}

	var h goldenHeader
	if err := json.Unmarshal(sc.Bytes(), &h); err != nil {
		t.Fatalf("first line of %s is not JSON: %v", path, err)
	}
	return h
}
