#!/usr/bin/env python3
"""Freeze the upstream Python's behaviour as golden vectors under ``testdata/``.

PLAN.md task 1.3. Every later milestone is tested against these files, and
``AGENTS.md`` is categorical about why: *"CI must never need Python or model
weights"*, and *"most of these behaviours are ones where a wrong implementation
returns a plausible answer rather than an error."* Without a corpus, the Go port
would be written by reading ``original/`` and asserting whatever the Go happens to
do -- which is how a port enshrines its own bugs.

Output is **JSONL**, one JSON object per line, first line a header record. Two
reasons rather than the pretty-JSON shape ``export_onnx.py --fixture`` uses:
``treefmt``'s prettier owns ``*.json`` and would reflow a pretty fixture on every
``just fmt``, and a line-per-case diff is reviewable where a reflowed blob is not
(task 1.3.7, R6).

Determinism (task 1.3.7): a fresh ``np.random.default_rng(seed)`` per case, never
torch's global stream -- ``DecisionModel.__init__`` randomly initialises the head
before ``load_state_dict`` overwrites it, so the global stream advances by an amount
that depends on which checkpoints were built. Cases are emitted in sorted name
order, ``torch.set_num_threads(1)``, CPU only.

Usage::

    .venv-ref/bin/python scripts/dump_python_parity.py --all
    just fmt && just ci

Regenerating is a reviewed diff, never a drive-by (``AGENTS.md``).
"""

from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import json
import math
import sys
import unicodedata
from decimal import Decimal
from pathlib import Path
from typing import Any

import numpy as np

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "original"))

SEED = 0
GENERATOR = "scripts/dump_python_parity.py"
COMMENT = (
    "Generated against the pinned reference environment (scripts/requirements-ref.txt). "
    "Do not hand-edit: regenerating this file is a reviewed diff (PLAN.md R6)."
)

CHECKPOINT_DIRS = {
    "english": "",
    "multilingual": "multilingual",
    "typed-decisions": "typed-decisions",
}


# --------------------------------------------------------------------------- header


def versions() -> dict[str, str]:
    """The pins that make the corpus meaningful.

    ``export_onnx.py``'s ``versions()`` omits ``tokenizers`` and ``safetensors``;
    task 1.3.6 needs both, and ``tokenizers`` is the one R6 actually names.
    """
    import safetensors
    import tokenizers
    import transformers

    return {
        "python": sys.version.split()[0],
        "transformers": transformers.__version__,
        "tokenizers": tokenizers.__version__,
        "numpy": np.__version__,
        "safetensors": safetensors.__version__,
    }


def torch_version() -> str:
    import torch

    return str(torch.__version__)


def torch_cpu_capability() -> str:
    """The ATen CPU kernel variant (DEFAULT/AVX2/AVX512) torch dispatches to."""
    import torch

    return str(torch.backends.cpu.get_cpu_capability())


def stable_seed(name: str) -> int:
    """A per-case seed that does not move between processes or Python versions."""
    return int(hashlib.sha256(name.encode()).hexdigest()[:8], 16)


def sha256_file(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def tokenizer_config_shas(models_root: Path) -> dict[str, str]:
    """Hash every ``tokenizer_config.json`` into the header.

    ``laya.Agent.__init__`` calls ``_fix_tokenizer_config`` (``agent.py:21-46``),
    which rewrites this file in place, so the local tree can stop matching the
    recorded Hub revision the first time the Python runs. At the pinned revision the
    function is a verified no-op for all three checkpoints -- hashing turns that
    from an assumption into something a regeneration would catch.
    """
    out = {}
    for name, sub in sorted(CHECKPOINT_DIRS.items()):
        p = models_root / "laya" / sub / "tokenizer" / "tokenizer_config.json"
        if p.is_file():
            out[name] = sha256_file(p)
    return out


def checkpoint_sha(models_root: Path) -> str | None:
    p = models_root / "PROVENANCE.json"
    if not p.is_file():
        return None
    return str(json.loads(p.read_text()).get("sha"))


# What produced the numbers. Section 8 of PLAN.md promises "within 1e-4 of PyTorch",
# and that tolerance is only meaningful against a stated device, dtype and attention
# implementation -- fp16 on a GPU under eager attention is a different claim entirely
# (task 1.7.2). The facts, not guesses: `device` because dump_logits never calls
# `.to(device)`, `dtype` from export_onnx.py:154's `model.float().eval()` (stored
# weights are fp16, the reference run is not), `attn` from the sdpa argument at
# dump_logits' build_decision_model call, and `torch_threads` from its
# `torch.set_num_threads(1)`.
#
# Every fixture carries it, including the six that never import torch. They are
# generated by the same pinned environment in the same run, and a header whose shape
# depends on which fixture it heads is a header no single test can check.
COMPUTE: dict[str, Any] = {
    "device": "cpu",
    "dtype": "float32",
    "attn": "sdpa",
    "torch_threads": 1,
}


def header(fixture: str, models_root: Path, **extra: Any) -> dict[str, Any]:
    h: dict[str, Any] = {
        "kind": "header",
        "fixture": fixture,
        "generator": GENERATOR,
        "versions": versions(),
        "checkpoint_sha": checkpoint_sha(models_root),
        "tokenizer_config_sha256": tokenizer_config_shas(models_root),
        "seed": SEED,
        "compute": COMPUTE,
        "comment": COMMENT,
    }
    h.update(extra)
    return h


def write_jsonl(path: Path, head: dict[str, Any], cases: list[dict[str, Any]]) -> None:
    """One header line, then cases in sorted name order (task 1.3.7).

    ``sort_keys`` stays off on purpose: ``criteria`` dict order is load-bearing --
    it is the order ``render_options`` renders in and the order ``system_one`` zips
    probabilities against -- so sorting keys would silently change the fixture's
    meaning. ``ensure_ascii=False`` keeps non-ASCII literal, which is what makes the
    diff reviewable; it does not change what a JSON decoder sees.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [json.dumps(head, ensure_ascii=False)]
    for c in sorted(cases, key=lambda c: c["name"]):
        lines.append(json.dumps({"kind": "case", **c}, ensure_ascii=False))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  {path}  ({len(cases)} cases)")


# ------------------------------------------------------------------ 1.3.1 tokenizer


# PLAN.md task 4.4's required case list. Each entry is (name, text); the record then
# carries both `text` and `" " + text`, because `common.py:68` tokenises every option
# with a leading space and the two checkpoints disagree about whether it survives.
#
# Task 4.4.9 (lone surrogates / invalid UTF-8) is deliberately **absent**. A lone
# surrogate cannot round-trip through JSON: Python emits "\ud800" and Go's decoder
# replaces it with U+FFFD, so the fixture would assert against a corrupted input. The
# task says "decide and document the boundary; sanitize at the API edge" -- this is
# that decision. Go tests it at the edge, without a golden vector.
def tokenizer_cases(mask_token: str) -> list[tuple[str, str]]:
    cases: list[tuple[str, str]] = []

    # 4.4.1 -- consecutive whitespace, the most common drift and crash site.
    for n, t in [
        ("empty", ""),
        ("space", " "),
        ("two-spaces", "  "),
        ("newline", "\n"),
        ("tab", "\t"),
        ("crlf", "\r\n"),
        ("mixed", "   \n   "),
    ]:
        cases.append((f"ws/{n}", t))

    # 4.4.5 -- runs of 2 to 24 spaces are added tokens on English (ids 50254-50275),
    # and `serialize_state` feeds arbitrary user JSON through the tokenizer, so
    # indentation runs are realistic input rather than a synthetic edge case.
    for n in (2, 3, 8, 16, 23, 24, 25):
        cases.append((f"ws/run-{n:02d}", "a" + " " * n + "b"))

    # 4.4.3 -- compact JSON exactly as `serialize_state` emits it.
    for n, obj in [
        ("flat", {"subject": "invoice 4411", "amount": 42}),
        ("nested", {"user": {"id": 7, "tags": ["a", "b"]}, "ok": True, "none": None}),
        ("escapes", {"q": 'he said "hi"\nand left\\', "tab": "a\tb"}),
        ("non-ascii", {"city": "München", "note": "café — 日本"}),
        ("long-array", {"xs": list(range(40))}),
    ]:
        cases.append((f"json/{n}", json.dumps(obj, ensure_ascii=False)))

    # 4.4.4 -- the mask literal inside user text. build_sequence scrubs it to " "
    # before tokenising, but the tokenizer must still be pinned on the raw form.
    cases.append(("mask/bare", mask_token))
    cases.append(("mask/mid-sentence", f"is this {mask_token} spam?"))

    # 4.4.5 -- added tokens, bare and mid-sentence.
    for n, t in [
        ("unused0", "<unused0>"),
        ("start-of-turn", "<start_of_turn>"),
        ("2mass", "<2mass>"),
        ("at-bos", "[@BOS@]"),
        ("ip-address", "|||IP_ADDRESS|||"),
    ]:
        cases.append((f"added/{n}-bare", t))
        cases.append((f"added/{n}-mid", f"before {t} after"))

    # 4.4.6 -- normalisation. English normalises NFC; multilingual does not normalise
    # beyond space -> U+2581, so these two legitimately produce different ids.
    for n, t in [
        ("nfc-e-acute", unicodedata.normalize("NFC", "café")),
        ("nfd-e-acute", unicodedata.normalize("NFD", "café")),
        ("fullwidth-a", "ＡＢＣ"),
        ("ligature-fi", "ﬁnal"),
        ("nbsp", "a b"),
        ("zwsp", "a​b"),
        ("zwj", "a‍b"),
        ("bom", "﻿hello"),
        ("combining", "áêĩ"),
    ]:
        cases.append((f"norm/{n}", t))

    # 4.4.7 -- emoji: ZWJ sequences, skin tones, flags. Byte fallback on multilingual.
    for n, t in [
        ("family-zwj", "\U0001f468‍\U0001f469‍\U0001f467"),
        ("skin-tone", "\U0001f44d\U0001f3fd"),
        ("flag", "\U0001f1e9\U0001f1ea"),
        ("mixed-text", "ship it \U0001f680 now"),
    ]:
        cases.append((f"emoji/{n}", t))

    # 4.4.8 -- scripts.
    for n, t in [
        ("devanagari", "मुंबई में बारिश"),
        ("arabic", "القاهرة مدينة"),
        ("cjk", "東京へようこそ"),
        ("thai", "สวัสดีครับ"),
        ("cyrillic", "Здравствуйте"),
        ("hangul-precomposed", "한국어"),
        ("hangul-jamo", "한국어"),
    ]:
        cases.append((f"script/{n}", t))

    # ---------------------------------------------------------------- 4.4.12
    # Corpus v2, the first M4 commit. The v1 cases above have **zero byte-fallback
    # coverage**: every emoji and script probe happens to be a single vocab entry on
    # multilingual, so the `<0xXX>` path -- the one stage most likely to be wrong in a
    # from-scratch BPE -- was pinned by nothing at all.

    # Byte fallback proper. These four are outside both vocabularies, so multilingual
    # must decompose them into one `<0xXX>` per UTF-8 byte.
    for n, t in [
        ("cjk-ext-b", "a\U0002000b b"),
        ("emoji-15", "\U0001fae8"),
        ("math-fraktur", "\U0001d518"),
        ("tangut", "\U00017000"),
    ]:
        cases.append((f"bytefall/{n}", t))

    # Unicode whitespace that is not ASCII space. The pre-tokenizer's \s is
    # Unicode-aware in Oniguruma and ASCII-only in Go's RE2 (R1), so these are exactly
    # where a Go scanner silently diverges. Both with and without a leading space,
    # because that is the `common.py:68` call shape.
    for n, t in [
        ("nbsp-run", "a\u00a0\u00a0b"),
        ("ideographic", "a\u3000b"),
        ("em-space-run", "a\u2003\u2003b"),
        ("em-space-lead", "\u2003\u2003b"),
        ("vertical-tab", "a\vb"),
        ("next-line", "a\u0085b"),
        ("line-sep", "a\u2028b"),
        ("ogham", "a\u1680b"),
    ]:
        cases.append((f"uws/{n}", t))

    # Contractions: the ByteLevel pattern splits "DON'T" into [DON, ', T] on the
    # straight quote, and the curly apostrophe is a different codepoint entirely.
    for n, t in [
        ("dont-upper", "DON'T"),
        ("dont-lower", "don't"),
        ("curly", "don\u2019t"),
        ("possessive", "the user's invoice"),
        ("ll-ve-re", "we'll they've you're it's I'm"),
    ]:
        cases.append((f"contract/{n}", t))

    # Added tokens directly adjacent to text, with no separating space. An added token
    # is matched before normalisation, so adjacency is where the split goes wrong.
    for n, t in [
        ("no-space-before", "x<unused0>"),
        ("no-space-after", "<unused0>x"),
        ("both-sides", "x<unused0>y"),
        ("doubled", "<unused0><unused0>"),
        ("in-json", '{"k": "<unused0>"}'),
    ]:
        cases.append((f"adj/{n}", t))

    # The mask literal's lstrip behaviour. `convert_ids_to_tokens` is what the dumper
    # records precisely because `Encoding.tokens` would return the lstripped slice
    # ("  [MASK]") and hide this.
    for n, t in [
        ("two-spaces-before", f"  {mask_token}"),
        ("text-then-mask", f"spam {mask_token}"),
        ("mask-then-text", f"{mask_token} spam"),
        ("mask-doubled", f"{mask_token}{mask_token}"),
    ]:
        cases.append((f"masklstrip/{n}", t))

    # The ByteLevel give-back, evaluated per added-token segment. `\s+(?!\S)`
    # hands its last character back to a following `\s+` only when the run is
    # followed by a non-space *inside the same segment* -- and an added token ends
    # the segment. Measured against the oracle: "a\t\t[unused0]" pre-tokenises the
    # run whole because it reaches the segment end, while "a\t\tX" splits it 1 + 1.
    # Nothing in 4.4.12's probe list reaches this, and it is the exact shape of bug
    # (a one-token shift) that moves every marker position after it.
    #
    # Both bracket styles are probed because the two checkpoints disagree about
    # which is an added token: "[unused0]" is one on English (id 50285) and plain
    # text on multilingual, "<unused0>" is one on multilingual (id 7) and plain
    # text on English. One spelling alone would test a segment boundary on one
    # checkpoint and ordinary text on the other, under a name claiming otherwise.
    for n, t in [
        ("tabs-then-en-added", "a\t\t[unused0]"),
        ("tabs-then-ml-added", "a\t\t<unused0>"),
        ("tabs-mid-segment", "a\t\tX"),
        ("tabs-at-text-end", "a\t\t"),
        ("tabs-before-mask", f"a\t\t{mask_token}"),
        ("spaces-then-en-added", "a   [unused0]"),
        ("spaces-then-ml-added", "a   <unused0>"),
        ("spaces-mid-segment", "a   X"),
    ]:
        cases.append((f"giveback/{n}", t))

    # Space runs past the added-token table. English has whitespace added tokens for
    # runs of 2..24 only, so 25 and up must fall back to the merge loop -- 48 and 49
    # straddle two table-width boundaries.
    for n in (48, 49):
        cases.append((f"ws/run-{n}", "a" + " " * n + "b"))

    # Tab and newline runs. The give-back rule in the ByteLevel pattern (a whitespace
    # run hands its last character to the following token) only shows up on runs.
    for n in (2, 26):
        cases.append((f"ws/tab-run-{n:02d}", "a" + "\t" * n + "b"))
    for n in (2, 3, 32):
        cases.append((f"ws/nl-run-{n:02d}", "a" + "\n" * n + "b"))

    # A literal U+2581 in user text, which collides with the Metaspace replacement
    # character multilingual uses for a space.
    cases.append(("lit/metaspace", "a\u2581\u2581b"))
    cases.append(("lit/metaspace-bare", "\u2581"))

    # C0 controls that are not whitespace.
    for n, t in [("nul", "a\x00b"), ("soh", "a\x01b"), ("del", "a\x7fb")]:
        cases.append((f"ctrl/{n}", t))

    # Digits: BPE splits number runs by merge rank, and laya's states are full of
    # invoice numbers and amounts.
    for n, t in [
        ("short", "42"),
        ("long", "1234567890"),
        ("mixed", "invoice 4411 for 1.50 EUR"),
        ("leading-zero", "007"),
    ]:
        cases.append((f"digit/{n}", t))

    # Ordinary prose, so the corpus is not entirely pathological.
    cases.append(("prose/en", "I was charged twice for invoice 4411, please refund it today."))
    cases.append(("prose/de", "Ich wurde zweimal für Rechnung 4411 belastet."))

    return cases


def dump_tokenizer(name: str, ckpt: str, models_root: Path, out_dir: Path) -> None:
    from transformers import AutoTokenizer

    tok_dir = models_root / "laya" / CHECKPOINT_DIRS[ckpt] / "tokenizer"
    tok = AutoTokenizer.from_pretrained(tok_dir)

    cases = []
    for case_name, text in tokenizer_cases(tok.mask_token):
        ids = tok(text, add_special_tokens=False)["input_ids"]
        ids_ls = tok(" " + text, add_special_tokens=False)["input_ids"]
        cases.append(
            {
                "name": case_name,
                "text": text,
                "ids": ids,
                # Token strings as well as ids: an id diff tells you nothing, while
                # ["a", "b"] vs ["ab"] names the stage that broke (AGENTS.md).
                "tokens": tok.convert_ids_to_tokens(ids),
                "ids_with_leading_space": ids_ls,
                "tokens_with_leading_space": tok.convert_ids_to_tokens(ids_ls),
            }
        )

    head = header(
        name,
        models_root,
        checkpoint=ckpt,
        specials={
            "mask_token": tok.mask_token,
            "mask_token_id": tok.mask_token_id,
            "cls_token_id": tok.cls_token_id,
            "sep_token_id": tok.sep_token_id,
            "pad_token_id": tok.pad_token_id,
            "unk_token_id": tok.unk_token_id,
        },
    )
    write_jsonl(out_dir / f"{name}.jsonl", head, cases)


# ------------------------------------------------------------------ 4.4.13 pretok


def dump_pretok(name: str, ckpt: str, models_root: Path, out_dir: Path) -> None:
    """Per-stage vectors: the normalizer's output and the pre-tokenizer's pieces.

    Task 4.4.13. The tokenizer_*.jsonl corpus pins the whole pipeline, which is
    what parity means -- but it can only be run against the real 3.5/34 MB
    tokenizer.json, so it is gated out of CI and a failure names no stage. These
    vectors are pure ``str -> str`` and ``str -> list[str]``: the Go normalizer,
    ByteLevel scanner and Metaspace can be tested against real Oniguruma output
    with no model files present, and a red case says which stage broke.

    Note the composition. ``pre_tokenize_str`` does **not** run the normalizer,
    so feeding it the raw text would record a pipeline laya never executes. It
    is fed ``normalized`` here, which is the order ``Tokenizer.encode`` uses and
    the order the Go code implements.

    Offsets ride along because they are what pins the give-back rule and the
    lstrip spans; Go does not compute them, but a human reading a failure does.
    """
    from transformers import AutoTokenizer

    tok_dir = models_root / "laya" / CHECKPOINT_DIRS[ckpt] / "tokenizer"
    tok = AutoTokenizer.from_pretrained(tok_dir)
    backend = tok.backend_tokenizer

    cases = []
    for case_name, text in tokenizer_cases(tok.mask_token):
        normalized = backend.normalizer.normalize_str(text)
        pieces = backend.pre_tokenizer.pre_tokenize_str(normalized)
        cases.append(
            {
                "name": case_name,
                "text": text,
                "normalized": normalized,
                "pretokens": [piece for piece, _ in pieces],
                "offsets": [[start, end] for _, (start, end) in pieces],
            }
        )

    head = header(
        name,
        models_root,
        checkpoint=ckpt,
        normalizer=json.loads(backend.normalizer.__getstate__())["type"],
        pre_tokenizer=json.loads(backend.pre_tokenizer.__getstate__())["type"],
    )
    write_jsonl(out_dir / f"{name}.jsonl", head, cases)


# --------------------------------------------------------------------- 1.3.3 render


def render_cases() -> list[dict[str, Any]]:
    """`render_criterion` / `render_options` / `serialize_state`, invariants 14-18.

    Ported from ``original/tests/test_criteria.py:33-100`` plus the golden cases
    ``docs/INVARIANTS.md`` #17 names. ``test_criteria.py:103-116`` is deliberately
    left out: it asserts five string literals are present in ``Agent.__init__`` via
    ``inspect.getsource``, which is not a behaviour a port can or should reproduce
    (PLAN.md task 7.3.11).

    Output is always a **string** (or a list of strings). Never a nested object: #17's
    ``{"d": "münchen"}`` -> literal-``ü`` case is only verifiable if the rendered text
    is carried as text.
    """
    from laya.common import render_criterion, render_options, serialize_state

    cases: list[dict[str, Any]] = []

    def crit(name: str, value: Any) -> None:
        cases.append(
            {
                "name": f"criterion/{name}",
                "fn": "render_criterion",
                "input": value,
                "output": render_criterion(value),
            }
        )

    crit("str-passthrough", "phishing or scam")
    crit("dict", {"desc": "phishing"})
    crit("list", ["a", "b"])
    crit("int", 3)
    crit("float", 3.5)
    crit("bool-false", False)
    crit("bool-true", True)
    crit("none", None)
    crit("non-ascii", {"d": "münchen"})
    crit("nested", {"a": {"b": [1, {"c": None}]}})
    crit("empty-string", "")
    crit("empty-dict", {})
    # `default=str` -- the json.dumps fallback for anything unserialisable (Go's
    # equivalent is the fmt.Sprintf("%v") fallback in Task 2.1.4). NOT `object()`:
    # its str() embeds a heap address, so the fixture would differ on every run.
    #
    # The *input* is recorded post-substitution, because a Python date or Decimal
    # cannot be written into JSON and Go could not construct one anyway. Feeding Go
    # the substituted form must produce the same output, which is the property worth
    # asserting; `original_types` says what was really passed in.
    for name, value, subst in [
        ("date", {"when": _dt.date(2026, 9, 20)}, {"when": "2026-09-20"}),
        ("decimal", {"amount": Decimal("1.50")}, {"amount": "1.50"}),
        ("complex", {"z": complex(1, 2)}, {"z": "(1+2j)"}),
    ]:
        cases.append(
            {
                "name": f"criterion/default-str-{name}",
                "fn": "render_criterion",
                "input": subst,
                "output": render_criterion(value),
                "original_types": {k: type(v).__name__ for k, v in value.items()},
                "note": "input recorded after json.dumps(default=str) substitution",
            }
        )

    def opts(name: str, q: dict[str, Any]) -> None:
        cases.append(
            {
                "name": f"options/{name}",
                "fn": "render_options",
                "input": q,
                "output": render_options(q),
            }
        )

    opts("choice/dict-desc", {"t": "choice", "ins": "x", "crit": {"billing": {"desc": "payments"}}})
    # 0 and False are legitimate criterion values; only None and "" mean "bare key".
    opts("choice/bare-forms", {"t": "choice", "ins": "x", "crit": {"tech": None, "sales": ""}})
    opts("choice/zero-and-false", {"t": "choice", "ins": "x", "crit": {"zero": 0, "no": False}})
    opts("choice/strings", {"t": "choice", "ins": "x", "crit": {"a": "first", "b": None}})
    opts(
        "choice/mixed", {"t": "choice", "ins": "x", "crit": {"a": {"n": 1}, "b": [1, 2], "c": 3.5}}
    )
    opts("choice/empty", {"t": "choice", "ins": "x", "crit": {}})
    opts("score/mixed-levels", {"t": "score", "ins": "x", "crit": [{"d": "low"}, "high", 2]})
    opts("score/strings", {"t": "score", "ins": "x", "crit": ["low", "high"]})
    opts("score/with-none", {"t": "score", "ins": "x", "crit": [{"a": 1}, [2], None]})
    opts("score/empty", {"t": "score", "ins": "x", "crit": []})
    opts("noul/defaults", {"t": "noul", "ins": "x", "crit": None})
    opts("noul/empty-dict", {"t": "noul", "ins": "x", "crit": {}})
    opts("noul/strings", {"t": "noul", "ins": "x", "crit": {"true": "yes it is", "false": "no"}})
    # Written true-first on purpose: the rendered order is fixed false=0, true=1
    # regardless of how the dict was written.
    opts(
        "noul/reversed-dict-order",
        {"t": "noul", "ins": "x", "crit": {"true": {"desc": "phishing"}, "false": {"desc": "ok"}}},
    )
    opts("noul/dict-criteria", {"t": "noul", "ins": "x", "crit": {"true": [1], "false": {"z": 0}}})
    # `score` with a dict criteria: enumerate() walks the KEYS, so the level text is
    # the key, not the value. Not an error upstream, just surprising -- pin it.
    opts("score/dict-criteria", {"t": "score", "ins": "x", "crit": {"low": 1, "high": 2}})

    def state(name: str, value: Any) -> None:
        cases.append(
            {
                "name": f"state/{name}",
                "fn": "serialize_state",
                "input": value,
                "output": serialize_state(value),
            }
        )

    state("str-passthrough", "just a string")
    state("str-with-braces", '{"not": "parsed"}')
    state("dict-flat", {"subject": "invoice 4411", "amount": 42})
    state("dict-nested", {"user": {"id": 7, "tags": ["a", "b"]}, "ok": True, "none": None})
    # Insertion order, not sorted: Go's encoding/json sorts map keys, which changes
    # the bytes the model sees (invariant #18).
    state("dict-unsorted-keys", {"z": 1, "a": 2, "m": 3})
    # No HTML escaping: encoding/json escapes <, > and & by default.
    state("dict-html-chars", {"html": "<b>a & b</b>"})
    state("dict-non-ascii", {"city": "München", "emoji": "\U0001f680"})
    state("list", [1, "two", {"three": 3}])
    state("empty-dict", {})
    state("empty-list", [])
    return cases


# ------------------------------------------------------------------- 1.3.6 mailtext


def mailtext_cases() -> list[dict[str, Any]]:
    """`clean_email_body` / `email_state` / `email_questions`, invariants 66-74.

    This block is the only one in ``docs/INVARIANTS.md`` with neither an upstream test
    nor a golden vector: ``original/tests/`` covers criteria, routing and e2e, and
    nothing covers ``email.py``. PLAN.md task 2.3.3 says to "write the tests this port
    deserves" -- writing them against vectors beats writing them against a reading of
    the regexes, which is how a Go bug becomes the expected answer.

    The signature cut is the part worth pinning: the scan window is
    ``range(max(1, min(int(len(lines) * 0.6), len(lines) - 8)), len(lines))``, so
    whether a sign-off is stripped depends on how long the message is.
    """
    from laya.email import clean_email_body, email_questions, email_state

    long_body = "\n".join(f"line {i} of the actual message body" for i in range(20))
    cases: list[dict[str, Any]] = []

    def body(name: str, text: str, max_chars: int | None = None) -> None:
        out = clean_email_body(text) if max_chars is None else clean_email_body(text, max_chars)
        rec: dict[str, Any] = {
            "name": f"clean/{name}",
            "fn": "clean_email_body",
            "input": text,
            "output": out,
        }
        if max_chars is not None:
            rec["max_chars"] = max_chars
        cases.append(rec)

    body("empty", "")
    body("plain", "Hello,\n\nplease refund invoice 4411.\n")
    body("crlf", "Hello,\r\n\r\nplease refund invoice 4411.\r\n")
    body("literal-backslash-n", "Hello,\\n\\nplease refund invoice 4411.")
    body("quoted-gt", "My reply.\n> their text\n> more of it\nstill mine.")
    body("quote-header-on-wrote", "My reply.\nOn Mon, someone wrote:\nold stuff here.")
    body("quote-header-original", "My reply.\n-- Original Message --\nold stuff.")
    body("quote-header-underscores", "My reply.\n________\nold stuff.")
    body("quote-header-from", "My reply.\nFrom: someone@example.com\nold stuff.")
    # A quote header on the FIRST line does not cut: `and lines` is falsy there.
    body("quote-header-first-line", "From: a@b.c\nthe whole message is here.")
    body("signature-dashes", long_body + "\n--\nChristian")
    body("signature-regards", long_body + "\nBest regards,\nChristian")
    body("signature-sent-from", long_body + "\nSent from my iPhone")
    # Counter-intuitive and therefore worth a vector: for a SHORT message the scan
    # window is at its widest, not its narrowest. `min(int(n*0.6), n - 8)` goes
    # negative below nine lines and `max(1, ...)` then pins the start at 1, so the
    # sign-off is stripped here while a longer message would have to reach 60% first.
    body("signature-short-body", "Thanks!\nBest regards,\nChristian")
    body("disclaimer-confidential", "Real content.\n\nThis email is confidential.")
    body(
        "disclaimer-received-in-error",
        "Real content.\n\nIf you received this email in error, delete it.",
    )
    body("collapse-spaces", "a    b\t\tc")
    body("blank-paragraphs", "one\n\n\n\ntwo")
    body("truncation", "x" * 50, 10)

    for name, kwargs in [
        ("minimal", {"subject": " Invoice ", "body": "Please refund.\n"}),
        ("with-sender", {"subject": "S", "body": "B", "sender": "a@b.c"}),
        ("clean-off", {"subject": "S", "body": "B\n> quoted", "clean": False}),
        ("extra-fields", {"subject": "S", "body": "B", "priority": "high", "dropped": None}),
        ("empty-subject", {"subject": None, "body": "B"}),
    ]:
        cases.append(
            {
                "name": f"state/{name}",
                "fn": "email_state",
                "input": kwargs,
                "output": email_state(**kwargs),
            }
        )

    cases.append(
        {
            "name": "questions/defaults",
            "fn": "email_questions",
            "input": None,
            "output": email_questions(),
        }
    )
    cases.append(
        {
            "name": "questions/custom-categories",
            "fn": "email_questions",
            "input": {"a": "first", "b": "second"},
            "output": email_questions({"a": "first", "b": "second"}),
        }
    )
    return cases


# ------------------------------------------------------------------- 1.3.2 sequence


def to_internal(qdef: dict[str, Any]) -> dict[str, Any]:
    """Replicate ``laya.Agent._to_internal`` (``agent.py:229-238``).

    Kept here rather than imported because ``Agent`` cannot be constructed without a
    checkpoint, and 1.3.2 needs no weights. A ``choice`` given a list becomes
    ``{label: None}``, which silently de-duplicates repeated labels.
    """
    t = qdef.get("type", "choice")
    crit = qdef.get("criteria")
    if t == "choice" and isinstance(crit, list):
        crit = {c: None for c in crit}
    ins = qdef.get("instructions", "")
    # The one place laya escapes non-ASCII: ensure_ascii is left at its default True
    # here, unlike every other json.dumps in the package (agent.py:236-237).
    if not isinstance(ins, str):
        ins = json.dumps(ins)
    return {"t": t, "ins": ins, "crit": crit}


def sequence_cases(ckpt: str, tok: Any, max_len: int, head_max_len: int) -> list[dict[str, Any]]:
    """The `(qtype, criteria, state, budget, order, direction)` matrix, invariants 1-12."""
    from laya.common import build_sequence, render_options

    long_state = {"body": " ".join(f"word{i}" for i in range(400)), "subject": "invoice 4411"}
    specs: list[tuple[str, dict[str, Any], Any, dict[str, Any]]] = [
        (
            "choice/basic",
            {
                "type": "choice",
                "instructions": "Which team?",
                "criteria": {"billing": "invoices", "tech": "bugs", "sales": None},
            },
            {"subject": "refund", "body": "charged twice"},
            {},
        ),
        (
            "choice/list-criteria",
            {
                "type": "choice",
                "instructions": "Pick one",
                "criteria": ["billing", "tech", "billing"],
            },
            "plain text state",
            {},
        ),
        (
            "choice/empty-criteria",
            {"type": "choice", "instructions": "Nothing", "criteria": {}},
            "state",
            {},
        ),
        (
            "score/basic",
            {
                "type": "score",
                "instructions": "How urgent?",
                "criteria": ["none", "soon", "blocking"],
            },
            {"body": "asap"},
            {},
        ),
        ("noul/defaults", {"type": "noul", "instructions": "Is this spam?"}, "buy now", {}),
        (
            "noul/criteria",
            {
                "type": "noul",
                "instructions": "Phishing?",
                "criteria": {"true": "scam", "false": "legit"},
            },
            "click here",
            {},
        ),
        # Invariant #6: 77 options at head_max_len=192 gives per=4 and a negative
        # opt_budget, so head_ids falls back to its floor of 8.
        (
            "choice/77-options",
            {
                "type": "choice",
                "instructions": "Overflow the head",
                "criteria": {f"k{i:02d}": f"desc {i}" for i in range(77)},
            },
            "s",
            {},
        ),
        (
            "choice/long-state",
            {"type": "choice", "instructions": "Which team?", "criteria": {"a": None, "b": None}},
            long_state,
            {},
        ),
        (
            "choice/truncate-left",
            {"type": "choice", "instructions": "Which team?", "criteria": {"a": None, "b": None}},
            long_state,
            {"truncate_left": True},
        ),
        # option_order is never passed in production (agent.py:261 uses the 5-arg
        # form) but it is in the signature, and it permutes marker semantics.
        (
            "choice/option-order",
            {
                "type": "choice",
                "instructions": "Reordered",
                "criteria": {"a": "one", "b": "two", "c": "three"},
            },
            "s",
            {"option_order": [2, 0, 1]},
        ),
        (
            "choice/tiny-max-len",
            {"type": "choice", "instructions": "Cramped", "criteria": {"a": "one", "b": "two"}},
            long_state,
            {"max_len": 32},
        ),
        (
            "choice/tiny-head",
            {
                "type": "choice",
                "instructions": "Cramped head",
                "criteria": {f"k{i}": f"a fairly long description {i}" for i in range(8)},
            },
            "s",
            {"head_max_len": 24},
        ),
        (
            "choice/state-list",
            {"type": "choice", "instructions": "Which team?", "criteria": {"a": None, "b": None}},
            [1, "two", {"three": 3}],
            {},
        ),
        (
            "choice/non-ascii",
            {
                "type": "choice",
                "instructions": "Welche Abteilung?",
                "criteria": {"buchhaltung": "Rechnungen", "technik": "Fehler"},
            },
            {"stadt": "München"},
            {},
        ),
        (
            "choice/mask-in-text",
            {
                "type": "choice",
                "instructions": f"Is {tok.mask_token} relevant?",
                "criteria": {"yes": None, "no": None},
            },
            {"body": f"contains {tok.mask_token} literal"},
            {},
        ),
    ]

    cases = []
    for name, qdef, state, kw in specs:
        q = to_internal(qdef)
        ml = kw.get("max_len", max_len)
        hml = kw.get("head_max_len", head_max_len)
        order = kw.get("option_order")
        tl = kw.get("truncate_left", False)
        ids, markers = build_sequence(tok, state, q, ml, hml, order, tl)
        cases.append(
            {
                "name": name,
                "checkpoint": ckpt,
                "state": state,
                "qdef": qdef,
                "q": q,
                "max_len": ml,
                "head_max_len": hml,
                "option_order": order,
                "truncate_left": tl,
                "ids": ids,
                "markers": markers,
                "n_options": len(render_options(q)),
                # agent.py:262-263 raises when these disagree; the Go port owes the
                # same error, so the fixture has to say when it fires.
                "markers_lost": len(render_options(q)) - len(markers),
            }
        )
    return cases


def dump_sequence(models_root: Path, out_dir: Path) -> None:
    from transformers import AutoTokenizer

    budgets = {"english": (512, 192), "multilingual": (1024, 256), "typed-decisions": (1024, 256)}
    cases: list[dict[str, Any]] = []
    for ckpt in sorted(CHECKPOINT_DIRS):
        tok_dir = models_root / "laya" / CHECKPOINT_DIRS[ckpt] / "tokenizer"
        tok = AutoTokenizer.from_pretrained(tok_dir)
        ml, hml = budgets[ckpt]
        for c in sequence_cases(ckpt, tok, ml, hml):
            c["name"] = f"{ckpt}/{c['name']}"
            cases.append(c)
    write_jsonl(out_dir / "sequence.jsonl", header("sequence", models_root), cases)


# -------------------------------------------------------------------- 1.3.4 answers


def answer_block(
    logit_row: list[float],
    act_row: list[float],
    temperature: list[float],
    temperature_by_options: dict[str, float],
    k: int,
    qtype: str,
    crit: Any,
    dtype: type = np.float32,
    sequential: bool = False,
    act_softmax: str = "numpy",
) -> dict[str, Any]:
    """Replicate ``agent.py:294-343`` for one question.

    Inlined rather than driven through ``Agent.system_one`` because there is no seam:
    the arithmetic lives inside the batch loop. ``dump_logits`` verifies this
    replication against a real ``Agent`` run rather than trusting it.

    ``act_row`` is **pre**-softmax, matching what the model emits; ``agent.py:295``
    softmaxes the whole tensor and then takes column 0.

    ``dtype`` is float32, as upstream computes. ``np.float64`` gives the obvious
    wrong port -- the float32 logits widened, then everything in float64 -- which
    the precision cases (Task 7.1.7) must round differently. ``sequential=True``
    replaces numpy's pairwise sums in the softmax and the entropy with a plain
    left-to-right loop, the other wrong port; the two differ only from k >= 8.

    ``act_softmax="torch"`` softmaxes the act row with torch's float32 CPU kernel,
    which is what agent.py:295 runs (D26). The default stays numpy so answers.jsonl
    is unchanged; the logits fixture's ``result_json`` uses torch.
    """
    from laya.common import QTYPES, confidence_from_probs, temp_bucket

    qt = QTYPES[qtype]
    t_scale = temperature_by_options.get(temp_bucket(qt, k), temperature[qt])
    # The head emits float32 logits, so a float64 port still starts from them.
    z = np.array(logit_row, dtype=np.float32).astype(dtype)[:k] / max(1e-3, float(t_scale))
    p = np.exp(z - z.max())
    p = p / (_seq_sum(p) if sequential else p.sum())

    a = np.array(act_row, dtype=np.float32)
    if act_softmax == "torch":
        import torch

        with torch.no_grad():
            a = torch.softmax(torch.from_numpy(a).float(), -1).numpy()
    elif act_softmax == "numpy":
        a = np.exp(a - a.max())
        a = a / a.sum()
    else:
        raise ValueError(f"act_softmax={act_softmax!r}")

    conf_score = round(_seq_confidence(p, k) if sequential else confidence_from_probs(p, k), 4)
    ext = {"act_probability": round(float(a[0]), 4)}

    if qtype == "choice":
        keys = list(crit.keys())
        # zip() without strict=: if the criteria and the marker count disagree the
        # upstream silently truncates to the shorter. Reproduced, not fixed.
        return {
            "type": "choice",
            "choice": keys[int(p.argmax())],
            "probabilities": {
                # noqa is the point: strict=True would raise where upstream truncates.
                kk: round(float(v), 4)
                for kk, v in zip(keys, p)  # noqa: B905
            },
            "confidence": conf_score,
            "action": ext,
        }
    if qtype == "score":
        return {
            "type": "score",
            "score": round(float((np.arange(k) * p).sum()), 4),
            "legend": {str(i): c for i, c in enumerate(crit)},
            "probabilities": {str(i): round(float(v), 4) for i, v in enumerate(p)},
            "confidence": conf_score,
            "action": ext,
        }
    return {
        "type": "noul",
        "noul": round(float(p[1]), 4),
        # NOT confidence_from_probs: for k=2 the two genuinely disagree (#26).
        "confidence": round(max(float(p[1]), 1.0 - float(p[1])), 4),
        "action": ext,
    }


def _seq_sum(a: np.ndarray) -> np.floating:
    """Left-to-right sum in the array's dtype, unlike numpy's pairwise add.reduce."""
    s = a.dtype.type(0)
    for v in a:
        s = s + v
    return s


def _seq_confidence(p: np.ndarray, k: int) -> float:
    """``confidence_from_probs`` (common.py:200-206) with a left-to-right entropy sum."""
    if k < 2:
        return 1.0
    p = p[:k]
    ent = -_seq_sum(p * np.log(np.clip(p, 1e-12, 1.0)))
    return float(np.clip(1.0 - ent / math.log(k), 0.0, 1.0))


def answers_cases(models_root: Path) -> list[dict[str, Any]]:
    """Synthetic logits through the answer path, invariants 22-32."""
    cfg_en = json.loads((models_root / "laya" / "rl_agent_config.json").read_text())
    temp = cfg_en["temperature"]
    # english carries every bucket; multilingual's is {} and exercises the fallback
    # to temperature[qtype], so both are represented.
    tbo_full = cfg_en["temperature_by_options"]
    tbo_empty: dict[str, float] = {}

    specs: list[tuple[str, str, Any, int, dict[str, float]]] = []
    # k sweeps the temp_bucket thresholds: 2, 3-5, 6-10, 11+.
    for k in (2, 3, 5, 6, 10, 11, 13):
        specs.append(
            (
                f"choice/k{k:02d}-buckets",
                "choice",
                {f"key{i}": f"desc {i}" for i in range(k)},
                k,
                tbo_full,
            )
        )
        specs.append(
            (
                f"choice/k{k:02d}-fallback",
                "choice",
                {f"key{i}": f"desc {i}" for i in range(k)},
                k,
                tbo_empty,
            )
        )
    for k in (2, 3, 6, 11):
        specs.append((f"score/k{k:02d}", "score", [f"level {i}" for i in range(k)], k, tbo_full))
        specs.append((f"noul/k{k:02d}", "noul", {"true": "yes", "false": "no"}, k, tbo_full))
    # #31: the legend carries the RAW criterion, so a dict criterion stays a dict.
    specs.append(("score/dict-legend", "score", [{"d": "low"}, "mid", 2], 3, tbo_full))
    # A choice whose criteria are shorter than k is deliberately NOT here. zip()
    # would truncate the probabilities and `keys[p.argmax()]` would then raise
    # IndexError -- but the state is unreachable through the public API, because
    # agent.py:262-263 raises ValueError when len(markers) != len(render_options(q)).
    # sequence.jsonl's `markers_lost` field is where that guard is pinned instead.

    cases: list[dict[str, Any]] = []
    for name, qtype, crit, k, tbo in specs:
        # NOT hash(name): Python randomises str hashing per process unless
        # PYTHONHASHSEED is set, so the corpus would differ on every run (1.3.7).
        rng = np.random.default_rng(SEED + stable_seed(name))
        logits = (rng.standard_normal(max(k, 4)) * 3.0).round(6).tolist()
        # Asymmetric on purpose: act_probability is column 0, and a 0/1 swap has to
        # be detectable (#32).
        act = [float(rng.standard_normal() * 2.0 + 1.5), float(rng.standard_normal() * 2.0 - 1.5)]
        ans = answer_block(logits, act, temp, tbo, k, qtype, crit)
        cases.append(
            {
                "name": name,
                "qtype": qtype,
                "k": k,
                "criteria": crit,
                "logits": logits,
                "act_logits": [round(v, 6) for v in act],
                "temperature": temp,
                "temperature_by_options": tbo,
                "answer": ans,
                # 7.4.2 compares the serialized bytes, not the parsed struct.
                "answer_json": json.dumps(ans, ensure_ascii=False, separators=(", ", ": ")),
            }
        )

    # Hand-injected, because no random sample produces them.
    def inject(
        name: str, qtype: str, crit: Any, k: int, logits: list[float], act: list[float]
    ) -> None:
        ans = answer_block(logits, act, temp, tbo_empty, k, qtype, crit)
        cases.append(
            {
                "name": name,
                "qtype": qtype,
                "k": k,
                "criteria": crit,
                "logits": logits,
                "act_logits": act,
                "temperature": temp,
                "temperature_by_options": tbo_empty,
                "answer": ans,
                "answer_json": json.dumps(ans, ensure_ascii=False, separators=(", ", ": ")),
            }
        )

    # A score of exactly 0.0. `Score` is a pointer field in Go precisely so that this
    # emits rather than being dropped as a zero value (docs/API.md:203-205).
    inject("score/exactly-zero", "score", ["a", "b", "c"], 3, [200.0, 0.0, 0.0], [1.0, -1.0])
    # k=2 under both confidence formulas: for a uniform p the entropy form gives 0.0
    # and noul's max(p1, 1-p1) gives 0.5. They must not be unified.
    inject("choice/k02-uniform", "choice", {"a": None, "b": None}, 2, [0.0, 0.0], [0.0, 0.0])
    inject("noul/k02-uniform", "noul", {"true": "y", "false": "n"}, 2, [0.0, 0.0], [0.0, 0.0])
    # A near-certain outcome: confidence saturates at 1.0 and the clip matters.
    inject("choice/saturated", "choice", {"a": None, "b": None}, 2, [50.0, -50.0], [9.0, -9.0])
    cases.extend(precision_cases(temp, tbo_full))
    return cases


# Task 7.1.7: one target per rounded field the float32 path feeds, against each
# wrong port. At four decimals a random sample almost never tells numpy's float32
# arithmetic from float64, or its pairwise sum from a sequential one, so every
# case above still passes under either port.
PRECISION_TARGETS: tuple[tuple[str, str, Any, int, str, str], ...] = (
    (
        "precision/choice-prob",
        "choice",
        {f"key{i}": f"desc {i}" for i in range(5)},
        5,
        "probabilities",
        "float64",
    ),
    (
        "precision/choice-confidence",
        "choice",
        {f"key{i}": f"desc {i}" for i in range(5)},
        5,
        "confidence",
        "float64",
    ),
    ("precision/score-value", "score", [f"level {i}" for i in range(6)], 6, "score", "float64"),
    ("precision/noul-value", "noul", {"true": "yes", "false": "no"}, 2, "noul", "float64"),
    # Pairwise and sequential sums first diverge at eight elements.
    (
        "precision/sum-order-prob",
        "choice",
        {f"key{i}": f"desc {i}" for i in range(10)},
        10,
        "probabilities",
        "sequential",
    ),
    (
        "precision/sum-order-confidence",
        "choice",
        {f"key{i}": f"desc {i}" for i in range(10)},
        10,
        "confidence",
        "sequential",
    ),
)
PRECISION_MAX_DRAWS = 200_000
PRECISION_PORTS: dict[str, dict[str, Any]] = {
    "float64": {"dtype": np.float64},
    "sequential": {"sequential": True},
}


def precision_cases(temp: list[float], tbo: dict[str, float]) -> list[dict[str, Any]]:
    """Cases whose rounded answer differs under a plausible wrong port.

    Each target draws seeded random logits until its field rounds differently under
    the port it names (``PRECISION_PORTS``), so the selection is the generator's, not
    a hand-picked value. ``discriminates`` names the field and ``against`` the port,
    and the Go side checks that the port really does get it wrong.
    """
    cases: list[dict[str, Any]] = []
    for name, qtype, crit, k, field, against in PRECISION_TARGETS:
        rng = np.random.default_rng(SEED + stable_seed(name))
        for _ in range(PRECISION_MAX_DRAWS):
            logits = (rng.standard_normal(max(k, 4)) * 3.0).round(6).tolist()
            act = [
                round(float(rng.standard_normal() * 2.0 + 1.5), 6),
                round(float(rng.standard_normal() * 2.0 - 1.5), 6),
            ]
            ans = answer_block(logits, act, temp, tbo, k, qtype, crit)
            wrong = answer_block(logits, act, temp, tbo, k, qtype, crit, **PRECISION_PORTS[against])
            if ans[field] != wrong[field]:
                break
        else:
            raise RuntimeError(f"{name}: no discriminating draw in {PRECISION_MAX_DRAWS}")
        cases.append(
            {
                "name": name,
                "qtype": qtype,
                "k": k,
                "criteria": crit,
                "logits": logits,
                "act_logits": act,
                "temperature": temp,
                "temperature_by_options": tbo,
                "answer": ans,
                "answer_json": json.dumps(ans, ensure_ascii=False, separators=(", ", ": ")),
                "discriminates": field,
                "against": against,
            }
        )
    return cases


# ---------------------------------------------------------------------- Round4 ties


def round4_cases() -> list[dict[str, Any]]:
    """`round(x, 4)` is half-to-even on the binary double; Go's math.Round is not.

    Invariant #29, and one of the four ``PLAN.md`` §5 singles out as causing silent
    wrong answers. It gets its own file because no sampled softmax output lands on a
    tie -- the values have to be chosen -- and because Task 2.1.5/2.1.6 implements
    ``Round4`` in ``jsonx`` long before any answer exists to apply it to.
    """
    values = [
        0.00125,
        0.00135,
        0.00115,
        -0.00125,
        -0.00135,
        2.5e-5,
        3.5e-5,
        1.5e-5,
        -2.5e-5,
        0.12345,
        0.123450001,
        0.98765,
        0.5,
        -0.5,
        0.0,
        -0.0,
        1.0,
        0.99995,
        0.99994999,
        1e-9,
        -1e-9,
        1 / 3,
        2 / 3,
        math.pi,
        math.e,
        1e10 + 0.00005,
    ]
    return [
        {
            "name": f"round4/{i:02d}",
            "input": v,
            # repr() pins the exact double the fixture means, independent of how a
            # JSON reader chooses to print it.
            "input_repr": repr(v),
            "output": round(v, 4),
            "output_repr": repr(round(v, 4)),
        }
        for i, v in enumerate(values)
    ]


# --------------------------------------------------------------- 7.1.8 f32math


# numpy's float32 exp and log are not libm: FLOAT_exp/FLOAT_log dispatch per CPU, and
# the golden vectors -- this file and answers.jsonl, whose softmax and entropy call
# them -- come from the X86_V3 (AVX2 + FMA3) instantiation of simd_exp_FLOAT /
# simd_log_FLOAT in loops_exponent_log.dispatch.c.src. X86_V4 runs the AVX512F
# instantiation and a baseline host runs npy_expf/npy_logf, both with different
# last bits, so regenerating on either would silently move the reference numbers.
F32_SIMD_TARGET = "X86_V3"


def f32_simd_target() -> str:
    """The dispatch target numpy runs for float32 exp and log on this host."""
    from numpy.lib.introspect import opt_func_info

    info = opt_func_info(func_name="^(exp|log)$", signature="float32")
    targets = {info[fn]["ff"]["current"] for fn in ("exp", "log")}
    if len(targets) != 1:
        raise SystemExit(f"exp and log dispatch to different targets: {sorted(targets)}")
    return targets.pop()


def require_f32_simd_target() -> None:
    got = f32_simd_target()
    if got != F32_SIMD_TARGET:
        raise SystemExit(
            f"numpy runs float32 exp/log as {got}, the golden vectors need "
            f"{F32_SIMD_TARGET}; regenerate on an AVX2+FMA3 host without AVX-512"
        )


def _bits(a: np.ndarray) -> list[str]:
    return [f"0x{int(b):08x}" for b in np.asarray(a, dtype=np.float32).view(np.uint32)]


def _f32(bits: list[int]) -> np.ndarray:
    return np.array(bits, dtype=np.uint32).view(np.float32)


def f32math_cases() -> list[dict[str, Any]]:
    """numpy's float32 exp and log, bit for bit (Task 7.1.8).

    Inputs and outputs are float32 bit patterns in hex, so neither JSON nor a
    float printer can round them. The ranges are the domains calib feeds the two
    functions -- exp gets z - max(z) <= 0 in the softmax, log gets p clipped to
    [1e-12, 1] in the entropy -- plus the rest of the line and each branch of the
    kernel: the overflow/underflow masks, the denormal scalef split, the
    denormal exponent/mantissa extraction and the sqrt(1/2) fold. The "softmax"
    records then run both through agent.py's softmax and confidence_from_probs.
    """
    cases: list[dict[str, Any]] = []

    def add(name: str, fn: str, x: np.ndarray) -> None:
        x = np.ascontiguousarray(x, dtype=np.float32)
        with np.errstate(all="ignore"):
            y = np.exp(x) if fn == "exp" else np.log(x)
        cases.append({"name": f"{fn}/{name}", "fn": fn, "in": _bits(x), "out": _bits(y)})

    def uniform(name: str, lo: float, hi: float, n: int) -> np.ndarray:
        rng = np.random.default_rng(stable_seed(name))
        return rng.uniform(lo, hi, n).astype(np.float32)

    def any_bits(name: str, n: int) -> np.ndarray:
        rng = np.random.default_rng(stable_seed(name))
        return rng.integers(0, 2**32, n, dtype=np.uint64).astype(np.uint32).view(np.float32)

    def around(bits: int, radius: int = 2) -> list[int]:
        return [bits + d for d in range(-radius, radius + 1)]

    xmax = 0x42B17218  # 88.72283935546875f
    xmin = 0xC2CFF1B5  # -103.97208404541015625f
    add("softmax-domain", "exp", uniform("exp/softmax-domain", -104.0, 0.0, 4096))
    add("near-zero", "exp", uniform("exp/near-zero", -1.0, 0.0, 1024))
    add("positive", "exp", uniform("exp/positive", 0.0, 89.0, 1024))
    add("any-bits", "exp", any_bits("exp/any-bits", 1024))
    # quadrant <= -125 takes fma_scalef_ps's denormal branch.
    add("denormal-result", "exp", uniform("exp/denormal-result", -104.0, -86.0, 512))
    edges = around(xmax) + around(xmin) + around(0xC2781E37)  # the kernel's worst ULP
    edges += [0x00000000, 0x80000000, 0x7F800000, 0xFF800000, 0x7FC00000, 0xFFC00000]
    edges += [0x00000001, 0x80000001, 0x3F800000, 0xBF800000, 0x3F317218, 0xBF317218]
    add("edges", "exp", _f32(edges))

    add("entropy-domain", "log", np.exp(uniform("log/entropy-domain", np.log(1e-12), 0.0, 4096)))
    add("unit", "log", uniform("log/unit", 0.0, 1.0, 1024))
    add("above-one", "log", np.exp(uniform("log/above-one", 0.0, np.log(1e6), 1024)))
    add("any-bits", "log", any_bits("log/any-bits", 1024))
    rng = np.random.default_rng(stable_seed("log/denormal"))
    add("denormal", "log", _f32(rng.integers(1, 0x00800000, 512).tolist()))
    sqrt_half = 0x3F3504F3  # NPY_SQRT1_2f, the fold boundary on the mantissa
    edges = around(sqrt_half) + around(sqrt_half + (1 << 23)) + around(0x3F486945)  # worst ULP
    edges += around(0x00800000) + around(0x3F800000)  # FLT_MIN, 1
    edges += [0x00000000, 0x80000000, 0x00000001, 0x007FFFFF, 0x7F7FFFFF, 0x7F800000]
    edges += [0xFF800000, 0x7FC00000, 0xFFC00000, 0xBF800000, 0x2B8CBCCC]  # 1e-12
    add("edges", "log", _f32(edges))

    # The same kernels as calib calls them: agent.py:305-307's softmax and
    # confidence_from_probs, compared in bits rather than after Round4, so that a
    # softmax or entropy still on libm's exp/log fails here even where
    # answers.jsonl's four decimals cannot see it.
    from laya.common import confidence_from_probs

    rng = np.random.default_rng(stable_seed("softmax/rows"))
    for i in range(64):
        k = int(rng.integers(2, 14))
        t = float(rng.choice([1.0, 0.5, 1.983399510383606]))
        logits = (rng.standard_normal(k) * 3.0).astype(np.float32)
        z = logits / max(1e-3, t)
        p = np.exp(z - z.max())
        p = p / p.sum()
        conf = confidence_from_probs(p, k)
        cases.append(
            {
                "name": f"softmax/{i:02d}",
                "fn": "softmax",
                "k": k,
                "temperature": t,
                "logits": _bits(logits),
                "probs": _bits(p),
                "confidence": conf,
                "confidence_repr": repr(conf),
            }
        )
    return cases


# ------------------------------------------------------------ 7.3.10 act_softmax


def _act_rows() -> list[tuple[str, np.ndarray]]:
    """[n, 2] float32 act-head logit rows, grouped by what each group probes.

    The act head's softmax is two-wide, so p[0] is 1/(1+e) or e/(1+e) with
    e = exp(-|a - b|): Round4 only moves where p[0] sits near a half boundary
    (k + 0.5)/1e4. "boundary" aims at those: for each sampled k it solves for the
    gap in float64, then takes the float32 neighbours of the second logit, so
    the rounded outputs straddle the boundary from both sides.
    """
    groups: list[tuple[str, np.ndarray]] = []

    rng = np.random.default_rng(stable_seed("act_softmax/boundary"))
    rows: list[tuple[float, float]] = []
    ks = rng.choice(10000, 400, replace=False)
    for k in sorted(int(k) for k in ks):
        t = (k + 0.5) / 1e4
        gap = math.log(t / (1.0 - t))
        a = np.float32(rng.uniform(-8.0, 8.0))
        bits = int(np.array([np.float64(a) - gap], dtype=np.float32).view(np.uint32)[0])
        for d in range(-3, 4):
            bb = np.array([bits + d], dtype=np.uint32).view(np.float32)[0]
            rows.append((float(a), float(bb)))
    groups.append(("boundary", np.array(rows, dtype=np.float32)))

    rng = np.random.default_rng(stable_seed("act_softmax/uniform"))
    a = rng.uniform(-10.0, 10.0, 1000)
    gap = rng.uniform(-20.0, 20.0, 1000)
    groups.append(("uniform", np.stack([a, a - gap], axis=1).astype(np.float32)))

    rng = np.random.default_rng(stable_seed("act_softmax/normal"))
    groups.append(("normal", (rng.standard_normal((500, 2)) * 3.0).astype(np.float32)))

    rng = np.random.default_rng(stable_seed("act_softmax/tiny"))
    a = rng.uniform(-4.0, 4.0, 200).astype(np.float32)
    ulps = rng.integers(-64, 65, 200).astype(np.int64)
    b = (a.view(np.uint32).astype(np.int64) + ulps).astype(np.uint32).view(np.float32)
    groups.append(("tiny-gap", np.stack([a, b], axis=1)))

    nz = -0.0
    f32 = np.float32
    edges = [
        (0.0, 0.0),
        (5.0, 5.0),
        (-3.0, -3.0),
        (0.0, nz),
        (nz, 0.0),
        (nz, nz),
        (100.0, 0.0),
        (0.0, 100.0),
        (-100.0, 0.0),
        (0.0, -100.0),
        (1e4, -1e4),
        (-1e4, 1e4),
        (1e4, 0.0),
        (0.0, 1e4),
        (1.0, float(np.nextafter(f32(1.0), f32(2.0)))),
        (float(np.nextafter(f32(1.0), f32(2.0))), 1.0),
        (0.0, 1e-7),
        (1e-7, 0.0),
        (0.0, 1e-45),
        (1e-45, 0.0),
        (88.0, -88.0),
        (-88.0, 88.0),
        (3e38, -3e38),
        (-3e38, 3e38),
        (3e38, 3e38),
        (9.2103, 0.0),  # p0 near 0.9999
        (0.0, 9.2103),
        (9.9035, 0.0),  # p0 near 0.99995, where Round4 reaches 1.0
        (0.0, 9.9035),
    ]
    groups.append(("edges", np.array(edges, dtype=np.float32)))
    return groups


def _act_wide_rows(width: int) -> np.ndarray:
    """[n, width] act-head rows for one head width (Task 7.3.10, wide heads).

    A checkpoint with k act_costs has a head k + 1 wide, and from eight on ATen's
    lastdim softmax leaves the lane-by-lane reduction for 8-wide chunks, a
    blended tail and a shuffle tree -- each of which fixes a different float32
    summation order. The rows vary magnitude, put the max in every lane
    (tail lanes included), tie several maxima, and aim p[0] at Round4 half
    boundaries as the two-wide "boundary" group does.
    """
    rng = np.random.default_rng(stable_seed(f"act_softmax/wide/{width}"))
    rows: list[np.ndarray] = []
    for _ in range(40):
        rows.append(rng.standard_normal(width) * 3.0)
    for _ in range(30):
        rows.append(rng.uniform(-30.0, 30.0, width))
    for _ in range(20):
        rows.append(rng.standard_normal(width) * 0.01)
    for j in range(40):
        r = rng.standard_normal(width) * 2.0
        r[j % width] = r.max() + rng.uniform(0.0, 2.0)
        rows.append(r)
    for j in range(20):
        r = rng.standard_normal(width) * 2.0
        top = float(np.float32(r.max() + 1.0))
        r[j % width] = top
        r[(j * 7 + 3) % width] = top
        rows.append(r)
    rows.append(np.zeros(width))
    rows.append(np.full(width, -0.0))
    rows.append(np.where(np.arange(width) % 2 == 0, 0.0, -0.0))
    rows.append(np.full(width, 7.25))
    out = [np.asarray(r, dtype=np.float32) for r in rows]
    if width >= 2:
        for _ in range(8):
            r = (rng.standard_normal(width) * 3.0).astype(np.float32)
            rest = float(np.exp(r[1:].astype(np.float64)).sum())
            t = (int(rng.integers(0, 10000)) + 0.5) / 1e4
            x0 = math.log(t / (1.0 - t)) + math.log(rest)
            bits = int(np.array([x0], dtype=np.float32).view(np.uint32)[0])
            for d in range(-2, 3):
                rr = r.copy()
                rr[0] = np.array([bits + d], dtype=np.uint32).view(np.float32)[0]
                out.append(rr)
    return np.stack(out).astype(np.float32)


ACT_WIDE_WIDTHS = tuple(range(1, 21)) + (32, 33)


def act_softmax_cases() -> list[dict[str, Any]]:
    """torch's float32 softmax over the act head's [n, w] logits (Task 7.3.10).

    agent.py:295 is ``torch.softmax(act.float(), -1)`` over the whole batch, and
    ``act_probability`` is ``round(float(act[r, 0]), 4)`` (agent.py:311). This is
    ATen's CPU softmax kernel, not numpy's exp, and answers.jsonl cannot tell the
    two apart: its act_probability values come from answer_block's numpy copy.
    The two-wide groups go through one matrix, as the agent's batch does, and
    each wider head width through its own; torch runs single-threaded on CPU.
    Logits and outputs are float32 bit patterns in hex.
    """
    import torch

    torch.set_num_threads(1)

    def softmax(mat: np.ndarray) -> np.ndarray:
        with torch.no_grad():
            return torch.softmax(torch.from_numpy(mat).float(), -1).cpu().numpy()

    def case(name: str, g: np.ndarray, pg: np.ndarray) -> dict[str, Any]:
        return {
            "name": f"act_softmax/{name}",
            "fn": "act_softmax",
            "act_logits": [_bits(r) for r in g],
            "p": [_bits(r) for r in pg],
            "act_probability": [round(float(r[0]), 4) for r in pg],
        }

    groups = _act_rows()
    p = softmax(np.concatenate([g for _, g in groups], axis=0))
    cases: list[dict[str, Any]] = []
    off = 0
    for name, g in groups:
        cases.append(case(name, g, p[off : off + len(g)]))
        off += len(g)
    for w in ACT_WIDE_WIDTHS:
        g = _act_wide_rows(w)
        cases.append(case(f"wide-w{w:02d}", g, softmax(g)))
    return cases


# torch's CPU softmax is not one kernel: ATen compiles SoftMaxKernel.cpp per CPU
# capability, and the AVX2 build's reduction order and Sleef exp are what
# calib.ActSoftmax ports. AVX512 reduces through a 16-lane shuffle tree and DEFAULT
# through scalar libm, so regenerating on either would silently move the reference
# bits -- the same trap F32_SIMD_TARGET closes for numpy.
TORCH_CPU_CAPABILITY = "AVX2"


def require_torch_cpu_capability(fixture: str = "act_softmax.jsonl") -> None:
    got = torch_cpu_capability()
    if got != TORCH_CPU_CAPABILITY:
        raise SystemExit(
            f"torch runs its CPU kernels as {got}, {fixture} needs "
            f"{TORCH_CPU_CAPABILITY}; regenerate on an AVX2 host without AVX-512 "
            f"(or with ATEN_CPU_CAPABILITY=avx2)"
        )


# ------------------------------------------------------------------- 7.1.6 ece


def _float_rec(key: str, v: float) -> dict[str, Any]:
    """A result that may be NaN, which JSON cannot carry: null plus a flag."""
    nan = math.isnan(v)
    return {key: None if nan else v, f"{key}_is_nan": nan, f"{key}_repr": repr(v)}


def ece_cases() -> list[dict[str, Any]]:
    """`ece_score` (common.py:187-197) and the plan's multi-class Brier score.

    Task 7.1.6. ECE is upstream's own function, called as is. Brier has no upstream
    counterpart; it is PLAN.md's definition for Task B.5.3 -- the mean over rows of
    sum_j (p_j - [j == y])^2, each row a float64 numpy array so that both sums are
    numpy's pairwise order -- computed here so the Go port has one reference.
    """
    from laya.common import ece_score

    cases: list[dict[str, Any]] = []

    def ece(name: str, conf: list[float], correct: list[bool], bins: int = 15) -> None:
        v = ece_score(np.array(conf, dtype=np.float64), np.array(correct, dtype=bool), bins)
        cases.append(
            {
                "name": f"ece/{name}",
                "fn": "ece_score",
                "conf": conf,
                "correct": correct,
                "bins": bins,
                **_float_rec("ece", v),
            }
        )

    def rand(name: str, n: int, bins: int = 15) -> None:
        rng = np.random.default_rng(stable_seed(name))
        conf = rng.random(n)
        correct = rng.random(n) < conf  # roughly calibrated, so no bin is trivially 0
        ece(name, [float(c) for c in conf], [bool(c) for c in correct], bins)

    ece("empty", [], [])
    ece("all-zero", [0.0, 0.0, 0.0], [True, False, True])
    ece("zero-and-half", [0.0, 0.5], [True, False])
    ece("one", [1.0], [True])
    ece("single", [0.73], [False])
    edges = [float(e) for e in np.linspace(0, 1, 16)]
    ece("on-every-edge", edges, [i % 2 == 0 for i in range(len(edges))])
    # Alternating labels, because with every answer correct the ECE is linear in
    # the confidences and cannot see which bin a value landed in. At 10 bins,
    # linspace's i*(1/10) differs from i/10 at edges 3, 6 and 7; at 49, i*(1/49)
    # misses 1.0 at the last edge, which linspace forces back to `stop`.
    for bins in (10, 49):
        edges = [float(e) for e in np.linspace(0, 1, bins + 1)]
        ece(f"on-every-edge-bins{bins}", edges, [i % 2 == 0 for i in range(bins + 1)], bins)
    ece("all-correct", [0.2, 0.4, 0.6, 0.8, 0.95], [True] * 5)
    ece("none-correct", [0.2, 0.4, 0.6, 0.8, 0.95], [False] * 5)
    for n in (7, 64, 200, 1000):
        rand(f"random-n{n}", n)
    rand("random-bins1", 50, 1)
    rand("random-bins10", 200, 10)

    def brier(name: str, probs: list[list[float]], labels: list[int]) -> None:
        if probs:
            rows = [
                np.sum((np.array(p, dtype=np.float64) - np.eye(len(p))[y]) ** 2)
                for p, y in zip(probs, labels, strict=True)
            ]
            v = float(np.mean(np.array(rows, dtype=np.float64)))
        else:
            v = float("nan")
        cases.append(
            {
                "name": f"brier/{name}",
                "fn": "brier",
                "probs": probs,
                "labels": labels,
                **_float_rec("brier", v),
            }
        )

    brier("empty", [], [])
    brier("certain-right", [[1.0, 0.0, 0.0]], [0])
    brier("certain-wrong", [[1.0, 0.0, 0.0]], [2])
    brier("uniform-k2", [[0.5, 0.5]], [1])
    for n, name in ((7, "random-n7"), (300, "random-n300")):
        rng = np.random.default_rng(stable_seed(f"brier/{name}"))
        probs, labels = [], []
        for _ in range(n):
            k = int(rng.integers(2, 14))  # ragged: choice k varies per question
            # Softmax output is float32; the caller widens it, so the fixture does too.
            z = rng.normal(size=k).astype(np.float32)
            p = np.exp(z - z.max())
            p = (p / p.sum()).astype(np.float32)
            probs.append([float(x) for x in p])
            labels.append(int(rng.integers(0, k)))
        brier(name, probs, labels)
    return cases


# --------------------------------------------------------------------- 1.3.5 logits


LOGITS_QUESTIONS: dict[str, dict[str, Any]] = {
    "category": {
        "type": "choice",
        "instructions": "Which team should handle the email in `body`?",
        "criteria": {
            "billing": "invoices, payments, refunds",
            "technical": "bugs, outages, integrations",
            "sales": "pricing, demos, new purchases",
            "other": "none of the above",
        },
    },
    "urgency": {
        "type": "score",
        "instructions": "How urgent is the request in `body`?",
        "criteria": ["no time pressure", "needs attention soon", "blocking issue"],
    },
    "is_spam": {"type": "noul", "instructions": "Is this email unsolicited spam?"},
}

LOGITS_STATES: list[tuple[str, Any]] = [
    (
        "en/billing",
        {"subject": "Duplicate charge", "body": "I was charged twice for invoice 4411."},
    ),
    ("en/technical", {"subject": "API 500s", "body": "Your API returns 500 on every POST."}),
    ("en/sales", {"subject": "Pricing", "body": "Can we see a demo and enterprise pricing?"}),
    ("en/spam", {"subject": "WIN NOW", "body": "Claim your free prize, click here!!!"}),
    (
        "de/billing",
        {"subject": "Doppelte Abbuchung", "body": "Rechnung 4411 wurde zweimal belastet."},
    ),
    ("ja/support", {"subject": "問い合わせ", "body": "ログインできません。"}),
    ("ar/billing", {"subject": "فاتورة", "body": "تم خصم المبلغ مرتين."}),
    ("plain-string", "The customer wants a refund for invoice 4411."),
    ("list-state", [{"role": "user", "text": "refund please"}, {"role": "agent", "text": "ok"}]),
    ("empty-body", {"subject": "", "body": ""}),
]


def dump_logits(models_root: Path, out_dir: Path, checkpoints: list[str]) -> None:
    """End-to-end ``(state, questions) -> (logits, act_logits)``, batch-level.

    Batch-level is not a convenience: ``collate_items`` derives ``L`` and ``kmax``
    from the whole batch, and the action features soft-max over the padded ``kmax``
    (``common.py:119-125``), so one question in isolation is a *different*
    computation. Every record therefore carries the whole ``questions`` dict.

    Only final outputs are stored. Invariants #35-38 (the manual head loop, the
    ``-1e4`` masking, the four act features) need intermediates, but they are only
    asserted if the head is reimplemented, which is M8 -- deferred post-1.0. Task 8.8
    regenerates with intermediates when it starts.

    ``result_json`` (Task 7.4.3) is the whole ``system_one`` envelope, built from
    this same forward pass through ``answer_block`` and serialized as
    ``answer_json`` is, so the fake-backend replay can compare it byte for byte.
    Each checkpoint's envelopes are cross-checked against a real ``laya.Agent``.
    """
    import torch
    from transformers import AutoTokenizer

    import laya

    sys.path.insert(0, str(REPO_ROOT / "scripts"))
    from export_onnx import build_decision_model

    from laya.common import build_sequence, collate_items, render_options

    torch.set_num_threads(1)

    cases: list[dict[str, Any]] = []
    for ckpt in checkpoints:
        ckpt_dir = models_root / "laya" / CHECKPOINT_DIRS[ckpt]
        cfg = json.loads((ckpt_dir / "rl_agent_config.json").read_text())
        tok = AutoTokenizer.from_pretrained(ckpt_dir / "tokenizer")
        print(f"  building {ckpt} ...", flush=True)
        model = build_decision_model(ckpt_dir, attn="sdpa")
        max_len, head_max_len = cfg.get("max_len", 512), cfg.get("head_max_len", 192)
        envelopes: list[tuple[str, Any, dict[str, Any]]] = []

        for state_name, state in LOGITS_STATES:
            items, qids = [], []
            for qid, qdef in LOGITS_QUESTIONS.items():
                q = to_internal(qdef)
                ids, markers = build_sequence(tok, state, q, max_len, head_max_len)
                # The same guard the Agent applies (agent.py:262-263). A fixture case
                # that silently dropped a marker would be a wrong golden vector.
                if len(markers) != len(render_options(q)):
                    raise SystemExit(
                        f"{ckpt}/{state_name}/{qid}: options exceed head_max_len="
                        f"{head_max_len}; upstream raises ValueError here"
                    )
                items.append({"ids": ids, "markers": markers, "qtype": QTYPES_MAP[q["t"]]})
                qids.append(qid)
            b = collate_items([items], tok.pad_token_id)
            with torch.no_grad():
                logits, act_logits = model(
                    b["input_ids"],
                    b["attention_mask"],
                    b["marker_pos"],
                    b["marker_mask"],
                    b["qtype"],
                    False,
                )
            lg, act = logits.float().numpy(), act_logits.float().numpy()
            envelope = {
                "model": "laya-rl-agent",
                "answers": {
                    qid: answer_block(
                        lg[r].tolist(),
                        act[r].tolist(),
                        # The Agent's defaults (agent.py:194-195): a checkpoint
                        # shipped without fitted temperatures still replays.
                        cfg.get("temperature", [1.0, 1.0, 1.0]),
                        cfg.get("temperature_by_options", {}),
                        len(items[r]["markers"]),
                        to_internal(LOGITS_QUESTIONS[qid])["t"],
                        to_internal(LOGITS_QUESTIONS[qid])["crit"],
                        act_softmax="torch",
                    )
                    for r, qid in enumerate(qids)
                },
                "usage": {"input_tokens": int(b["attention_mask"].sum()), "output_tokens": 0},
            }
            envelopes.append((f"{ckpt}/{state_name}", state, envelope))
            cases.append(
                {
                    "name": f"{ckpt}/{state_name}",
                    "checkpoint": ckpt,
                    "state": state,
                    "questions": LOGITS_QUESTIONS,
                    "qids": qids,
                    "qtypes": [QTYPES_MAP[to_internal(LOGITS_QUESTIONS[q])["t"]] for q in qids],
                    # #33: summed over the WHOLE batch, not per question.
                    "input_tokens": int(b["attention_mask"].sum()),
                    # Task 1.7.1. The five tensors the forward actually consumes, so
                    # Task 5.3 (`Collate`) can be asserted without a forward pass and
                    # the fake backend (6.1.2) can key on them. collate_items returns
                    # two more that are deliberately left out: `label`, which is a
                    # constant [-1, -1, -1] because no item here carries one, and
                    # `meta`, which after its key filter restates `qtype` and nothing
                    # else. `target` is absent upstream -- has_target is False.
                    # Shapes are batch-derived, which is the whole point: L and kmax
                    # come from the widest row in the group (common.py:222-223).
                    "collated": {
                        k: tensor_rec(b[k].numpy())
                        for k in (
                            "input_ids",
                            "attention_mask",
                            "marker_pos",
                            "marker_mask",
                            "qtype",
                        )
                    },
                    "logits": tensor_rec(logits.float().numpy()),
                    "act_logits": tensor_rec(act_logits.float().numpy()),
                    "result_json": _result_json(envelope),
                }
            )
        del model

        # The envelope is a hand-built copy of agent.py:240-343; check it against the
        # real thing before it becomes a golden vector.
        agent = laya.load(str(ckpt_dir), device="cpu")
        bad = []
        for name, state, envelope in envelopes:
            want = agent.system_one(state, LOGITS_QUESTIONS)
            # Serialized, not ==: dict equality would miss a key-order drift.
            if _result_json(envelope) != _result_json(want):
                bad.append(f"{name}:\n      copy {envelope}\n      real {want}")
        del agent
        if bad:
            raise SystemExit("result_json verification FAILED:\n    " + "\n    ".join(bad))
        print(f"  result_json matches laya.Agent.system_one on all {len(envelopes)} states")

    head = header(
        "logits",
        models_root,
        torch=torch_version(),
        note=(
            "Final outputs only. Invariants 35-38 need head intermediates and are "
            "only asserted if the head is reimplemented (M8, deferred); PLAN.md task "
            "8.8 regenerates this file with intermediates when it starts."
        ),
    )
    write_jsonl(out_dir / "logits.jsonl", head, cases)


def _result_json(envelope: dict[str, Any]) -> str:
    """Task 7.4.3's serialization: the separators and ensure_ascii answer_json uses."""
    return json.dumps(envelope, ensure_ascii=False, separators=(", ", ": "))


def tensor_rec(a: np.ndarray) -> dict[str, Any]:
    return {"dtype": str(a.dtype), "shape": list(a.shape), "data": a.reshape(-1).tolist()}


QTYPES_MAP = {"choice": 0, "score": 1, "noul": 2}


# ---------------------------------------------------------------------------- main


def verify_answer_block(models_root: Path) -> None:
    """Check `answer_block` against a real `Agent.system_one` before trusting it.

    ``answers.jsonl`` is generated by a hand-inlined copy of ``agent.py:294-343``,
    because the arithmetic has no seam -- it lives inside the batch loop. A copy that
    drifts from the original would produce a corpus that is internally consistent and
    wrong, which is the worst possible outcome for a parity fixture. So: run the real
    ``Agent`` once, run the copy on the same forward pass, and compare every field.
    """
    import torch
    from transformers import AutoTokenizer

    import laya
    from laya.common import build_sequence, collate_items

    torch.set_num_threads(1)
    ckpt_dir = models_root / "laya"
    cfg = json.loads((ckpt_dir / "rl_agent_config.json").read_text())
    state = {"subject": "Duplicate charge", "body": "I was charged twice for invoice 4411."}

    agent = laya.load(str(ckpt_dir), device="cpu")
    want = agent.system_one(state, LOGITS_QUESTIONS)["answers"]

    # The same forward pass, driven by hand, then through the inlined copy.
    tok = AutoTokenizer.from_pretrained(ckpt_dir / "tokenizer")
    items, qids = [], []
    for qid, qdef in LOGITS_QUESTIONS.items():
        q = to_internal(qdef)
        ids, markers = build_sequence(
            tok, state, q, cfg.get("max_len", 512), cfg.get("head_max_len", 192)
        )
        items.append({"ids": ids, "markers": markers, "qtype": QTYPES_MAP[q["t"]]})
        qids.append(qid)
    b = collate_items([items], tok.pad_token_id)
    with torch.no_grad():
        logits, act = agent.model(
            b["input_ids"],
            b["attention_mask"],
            b["marker_pos"],
            b["marker_mask"],
            b["qtype"],
            False,
        )
    logits, act = logits.float().numpy(), act.float().numpy()

    bad = []
    for r, qid in enumerate(qids):
        q = to_internal(LOGITS_QUESTIONS[qid])
        got = answer_block(
            logits[r].tolist(),
            act[r].tolist(),
            cfg.get("temperature", [1.0, 1.0, 1.0]),
            cfg.get("temperature_by_options", {}),
            len(items[r]["markers"]),
            q["t"],
            q["crit"],
        )
        if got != want[qid]:
            bad.append(f"{qid}:\n      copy {got}\n      real {want[qid]}")
    if bad:
        raise SystemExit("answer_block verification FAILED:\n    " + "\n    ".join(bad))
    print(f"  answer_block matches laya.Agent.system_one on all {len(qids)} questions")


FIXTURES = (
    "tokenizer_en",
    "tokenizer_ml",
    "pretok_en",
    "pretok_ml",
    "sequence",
    "render",
    "answers",
    "round4",
    "ece",
    "f32math",
    "mailtext",
    "logits",
    "act_softmax",
)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--fixture", choices=FIXTURES, action="append", default=[])
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--models-root", type=Path, default=REPO_ROOT / "models")
    ap.add_argument("--out", type=Path, default=REPO_ROOT / "testdata")
    ap.add_argument(
        "--checkpoint",
        choices=sorted(CHECKPOINT_DIRS),
        action="append",
        default=[],
        help="restrict the logits fixture; the others always cover every checkpoint",
    )
    ap.add_argument(
        "--act-softmax",
        action="store_true",
        help="only the act head's torch softmax fixture (same as --fixture act_softmax)",
    )
    ap.add_argument(
        "--verify-agent",
        action="store_true",
        help="cross-check answer_block against laya.Agent (needs weights)",
    )
    args = ap.parse_args()
    if args.act_softmax:
        args.fixture.append("act_softmax")

    wanted = list(FIXTURES) if args.all or not args.fixture else args.fixture
    print(json.dumps(versions(), indent=2))

    if "tokenizer_en" in wanted:
        dump_tokenizer("tokenizer_en", "english", args.models_root, args.out)
    if "tokenizer_ml" in wanted:
        dump_tokenizer("tokenizer_ml", "multilingual", args.models_root, args.out)
    if "pretok_en" in wanted:
        dump_pretok("pretok_en", "english", args.models_root, args.out)
    if "pretok_ml" in wanted:
        dump_pretok("pretok_ml", "multilingual", args.models_root, args.out)
    if "sequence" in wanted:
        dump_sequence(args.models_root, args.out)
    if "render" in wanted:
        write_jsonl(args.out / "render.jsonl", header("render", args.models_root), render_cases())
    if "answers" in wanted:
        require_f32_simd_target()
        write_jsonl(
            args.out / "answers.jsonl",
            header("answers", args.models_root),
            answers_cases(args.models_root),
        )
    if "round4" in wanted:
        write_jsonl(args.out / "round4.jsonl", header("round4", args.models_root), round4_cases())
    if "ece" in wanted:
        write_jsonl(args.out / "ece.jsonl", header("ece", args.models_root), ece_cases())
    if "f32math" in wanted:
        require_f32_simd_target()
        write_jsonl(
            args.out / "f32math.jsonl",
            header("f32math", args.models_root, simd=f32_simd_target()),
            f32math_cases(),
        )
    if "mailtext" in wanted:
        write_jsonl(
            args.out / "mailtext.jsonl", header("mailtext", args.models_root), mailtext_cases()
        )
    if "act_softmax" in wanted:
        require_torch_cpu_capability()
        write_jsonl(
            args.out / "act_softmax.jsonl",
            header(
                "act_softmax",
                args.models_root,
                torch=torch_version(),
                torch_cpu_capability=torch_cpu_capability(),
            ),
            act_softmax_cases(),
        )
    if args.verify_agent:
        verify_answer_block(args.models_root)
    if "logits" in wanted:
        require_torch_cpu_capability("logits.jsonl")
        cks = args.checkpoint or sorted(CHECKPOINT_DIRS)
        dump_logits(args.models_root, args.out, cks)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
